### ISSUE TITLE
handle letscrypt cert issuance/renewal within the nginx docker container

### ISSUE THREAD

**Issue by karlkeefer** [karlkeefer/pngr#11]
Otherwise people will get stuck on this relatively tricky configuration step.

**Comment by Lebski** [comment]
I'd suggest to add the [certbot](https://hub.docker.com/r/certbot/certbot/) to docker-compose file

**Comment by karlkeefer** [comment]
I think this image has a decent approach: https://github.com/staticfloat/docker-nginx-certbot

Planning to try it next time I actually deploy something forked from this "starter kit" to production.

**Comment by karlkeefer** [comment]
Wontfix unless other ask for it again later... I've deployed this a few places and never yet wanted the cert issuance/update to happen inside of docker.
