### ISSUE TITLE
GitHub Actions for CI

### ISSUE THREAD

**Issue by veeral-patel** [karlkeefer/pngr#13]
I'd like the ability to clone this repo, start hacking, push code to my repository and have a GitHub Actions pipeline run. The pipeline could be really simple, like just running my backend tests.

Being able to edit an existing GitHub Actions config file is way easier than trying to set everything up from scratch.

**Comment by karlkeefer** [comment]
Related to https://github.com/karlkeefer/pngr/issues/3

I have never actually used GitHub Actions - always just CircleCI - will do some digging here.
I agree that CI of some type is something that should be included.

**Comment by veeral-patel** [comment]
@karlkeefer I'm not wedded to GitHub Actions! As long as there's some CI built in and it's fairly popular, cloud-hosted, and cheap, I'd be happy with it!

Thanks!

**Comment by karlkeefer** [comment]
Closing as this is sufficiently similar to #3 - hoping to get an easy circleci recipe sorted on my next project forked from this.
