### ISSUE TITLE
Postgres image will not build from new Debian base image

### ISSUE THREAD

**Issue by DylanNWatt** [karlkeefer/pngr#15]
It appears that the Postgres Dockerfile was switched to use debian base instead of alpine, but the alpine `apk` package management was left in, so the image no longer builds.

![image](https://user-images.githubusercontent.com/1738085/69487310-9edbb880-0e25-11ea-97ee-63e21dbe9fc8.png)

**Comment by karlkeefer** [comment]
Sorry for the headache here - pushing a fix in a moment.
