### ISSUE TITLE
Docker build error 

### ISSUE THREAD

**Issue by nyousefzai** [karlkeefer/pngr#24]
# github.com/hashicorp/go-multierror
root/go/src/github.com/hashicorp/go-multierror/multierror.go:112:9: undefined: errors.As
root/go/src/github.com/hashicorp/go-multierror/multierror.go:117:9: undefined: errors.Is
# github.com/golang-migrate/migrate/source/httpfs
root/go/src/github.com/golang-migrate/migrate/source/httpfs/partial_driver.go:148:6: undefined: errors.As
ERROR: Service 'postgres' failed to build: The command '/bin/sh -c go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate && cp /root/go/bin/migrate /bin/migrate' returned a non-zero code: 2

**Comment by karlkeefer** [comment]
Thanks for reporting - I'll see if I can patch it up soon!
