### ISSUE TITLE
Enable Github Discussions for the repository

### ISSUE THREAD

**Issue by canrozanes** [karlkeefer/pngr#39]
I wanted to ask a couple of questions on how to do certain things but noticed discussions are not enabled for the repository.

Can we enable them?

[Here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) is the link of how to do it.

**Comment by karlkeefer** [comment]
https://github.com/karlkeefer/pngr/discussions

Curious to hear your questions :)
