### ISSUE TITLE
Bump react router to v6

### ISSUE THREAD

**Issue by canrozanes** [karlkeefer/pngr#58]
[Here](https://reactrouter.com/en/main/upgrading/v5) is the migration guide. It's pretty straightforward.

I can probably take this on!

**Comment by karlkeefer** [comment]
Awesome 🙌 I welcome the upgrade!

This project only has a few routes that use params or redirects, so hopefully it's a breeze to implement.

**Comment by karlkeefer** [comment]
I just merged a big upgrade to `react-scripts 5` and node v16.

@canrozanes is this is still something you're willing to contribute?

**Comment by canrozanes** [comment]
I just opened a PR https://github.com/karlkeefer/pngr/pull/62

**Comment by karlkeefer** [comment]
Thanks for doing this @canrozanes 🙇‍♂️
