### ISSUE TITLE
Migrate front-end build tooling from CRA to Vite

### ISSUE THREAD

**Issue by canrozanes** [karlkeefer/pngr#63]
create-react-app and by extension craco is no longer recommended in React docs.

[Here](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741) is a relevant comment from React maintainer Dan Abramov on shortcomings of create-react-app and it's future.

Lots of articles recommend switching to Vite and I switched to Vite in my project that I forked from this repo and it worked well for me. So I'd suggest moving in that direction.

**Comment by karlkeefer** [comment]
The main thing Craco was pulled in for was handling the "theme" build step of semanti-ui-react. That utilizes `.less` (or `.scss`) or some other css pre-processor thing.

If we could configure vite to still do that, then the switch seems like a no-downside one.

When you migrated did you start by `ejecting` your CRA-based thing?
Can you share the vite config you landed on?

**Comment by canrozanes** [comment]
Oh I did remove less from my app but it [seems](https://vite-plugin-ssr.com/sass) vite supports `.less` no less (pun intended).

My vite config looks like this:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import viteTsconfigPaths from "vite-tsconfig-paths";
import svgrPlugin from "vite-plugin-svgr";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), viteTsconfigPaths(), svgrPlugin()],
  server: {
    host: true,
    port: 3000,
    hmr: {
      host: 'localhost',
      protocol: 'wss',
      path: '/vite-development-wss'
    }
  },
});
```

and I had to rename the location inside nginx/nginx.conf to

```
 location /vite-development-wss {
      proxy_pass http://react;
      proxy_redirect off;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
    }
```

**Comment by karlkeefer** [comment]
I've updated pngr to use vite - had to do some funky stuff to get semantic-ui-less to build but still way cleaner than the craco setup.

Also managed to bump react to v18, setup test runner, and tweaked dockerfile to keep ci happy.

Thanks for the issue and configs - big help.
