### ISSUE TITLE
faster react container startup

### ISSUE THREAD

**Issue by karlkeefer** [karlkeefer/pngr#7]
`npm install` makes it take forever for the react dev server to start.

Had to do it this way to avoid requiring container rebuild anytime you added a package... not sure if there's a better way.

Related issue: Probably should have helpers or documentation for running NPM commands _in_ the container(!) for folks that don't have local npm setup and configured

**Comment by Lebski** [comment]
I made use of dockers caching mechanism. If there are no new imports, the build will be fast. https://github.com/karlkeefer/pngr/pull/19

**Comment by karlkeefer** [comment]
#22
